export const MarketData = [
  "Atta & Flour",
  "Rice",
  "Pulses & Lentils",
  "Cooking Oil & Ghee",
  "Sugar & Sweeteners",
  "Salt & Spices",
  "Tea & Coffee",
  "Beverages",
  "Juices",
  "Soft Drinks",
  "Energy Drinks",
  "Mineral Water",

  "Biscuits & Snacks",
  "Chocolates & Candy",
  "Bakery",
  "Cookies",
  "Cakes",
  "Namkeen",
  "Chips",
  "Popcorn",

  "Milk & Dairy",
  "Cheese & Butter",
  "Yogurt",
  "Milk Powder",
  "Cream",
  "Paneer",
  "Lassi",
  "Butter Milk",

  "Eggs",
  "Frozen Foods",
  "Frozen Vegetables",
  "Frozen Snacks",
  "Ice Cream",
  "Frozen Meat",

  "Fruits",
  "Vegetables",
  "Fresh Fruits",
  "Fresh Vegetables",
  "Herbs",
  "Exotic Fruits",
  "Seasonal Fruits",

  "Baby Care",
  "Personal Care",
  "Health & Wellness",
  "Toiletries",
  "Soap & Body Wash",
  "Shampoo & Conditioner",
  "Oral Care",
  "Skin Care",
  "Hair Care",
  "Deodorants",
  "Sanitary Products",

  "Laundry",
  "Cleaning Supplies",
  "Dishwashing",
  "Detergents",
  "Floor Cleaners",
  "Toilet Cleaners",
  "Glass Cleaners",
  "Disinfectants",

  "Stationery",
  "Pet Food",
  "Pet Care",
  "Pet Accessories",

  "Canned Food",
  "Dry Fruits & Nuts",
  "Pickles & Sauces",
  "Dates & Dried Fruits",
  "Seeds",
  "Superfoods",

  "Noodles & Pasta",
  "Sauces & Ketchup",
  "Jam & Honey",
  "Breakfast Cereals",
  "Oats",
  "Muesli",
  "Corn Flakes",

  "Meat & Poultry",
  "Seafood",
  "Mutton",
  "Chicken",
  "Beef",
  "Fish",
  "Prawns",

  "Kitchen Essentials",
  "Disposable Items",
  "Tissue Paper",
  "Aluminium Foil",
  "Cling Film",
  "Paper Cups",
  "Plastic Bags",

  "Organic Products",
  "Imported Products",
  "Gluten Free",
  "Sugar Free",
  "Low Fat Products",
  "Diabetic Friendly",

  "Spices Mix",
  "Ready to Eat Meals",
  "Instant Foods",
  "Masala Packs",
  "Sambar Powder",
  "Biryani Masala",

  "Cigarettes & Tobacco",
  "Pan Masala",
  "Betel Leaves",

  "Dairy Whitener",
  "Condensed Milk",
  "Gulab Jamun Mix",

  "Baking Products",
  "Flour Mixes",
  "Essences & Flavors",

  "Hand Wash",
  "Face Wash",
  "Moisturizer",
  "Sunscreen",

  "Insecticides",
  "Air Freshener",
  "Mosquito Repellent",

  "Other",
];
